version: '3.8'

services:
  spring-boot-app:
    container_name: my-spring-boot-app
    image: soyeonii/iruda-server
    restart: always
    ports:
      - "8080:8080"

  nginx:
    container_name: my-nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - spring-boot-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_log:/var/log/nginx